version: "3"

services:
  node-app:
    environment:
      - NODE_ENV=development
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start-dev